[package]
name = "scrappey-resolverr-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
async-trait = "0.1.89"
axum = "0.8.9"
base64 = "0.22.1"
chrono = "0.4.44"
env_logger = "0.11.10"
log = "0.4.29"
reqwest = "0.13.3"
serde = "1.0.228"
serde_json = "1.0.150"
thirtyfour = "0.37.0"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "signal"] }
transparent = "0.4.2"
ua_generator = "0.5.62"
url = "2.5.8"
uuid = { version = "1.23.1", features = ["v4"] }
