version: "3"
services:
  proxy:
    image: yegor256/squid-proxy
    restart: always
    ports:
      - "8081:3128"
    environment:
      - USERNAME=username
      - PASSWORD=password

  scrappey-resolverr:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - scrappey-resolverr:latest
    depends_on:
      - proxy
    environment:
      - SCRAPPEY_API_KEY=apikey # Your Scrappey API key (Required)
      # - HOST=0.0.0.0 # Listen on all interfaces (Default: 0.0.0.0)
      # - PORT=8191 # Flaresolverr port (Default: 8191)
      # - DATA_PATH=/data/persistent.json # Path to store cookies and other data (Default: /data/persistent.json)
      # - CAPTURE_FAILURE_SCREENSHOTS=true # Capture screenshots on failure (Default: true)
      # - SCREENSHOT_DIR=/data/screenshots # Directory to store screenshots (Default: /data/screenshots)
      # - MAX_FAILURE_SCREENSHOTS=10 # Maximum number of failure screenshots to keep (Default: 10)
      - PROXY_HOST=proxy # Proxy hostname accessible from container (Required - use service name for docker network)
      - PROXY_PORT=8081 # Port of the proxy (Required)
      - PROXY_USERNAME=username # Proxy authentication username (Optional - comment out if proxy doesn't need auth)
      - PROXY_PASSWORD=password # Proxy authentication password (Optional - comment out if proxy doesn't need auth)
    volumes:
      - ./data:/data # For cookies and other data
    ports:
      - "8191:8191"
